name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # volta로 맞춘 Node 버전 사용

    - name: Install dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v13.1.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        PROJECT_ID: coffeebara-front
